[preview]
ueberzug_offset = [-0.5, 1, 0.0, 0.0]

[opener]
vim = [
    { run = "vim %s", block = true }
]
explorer = [
	{ run = "xdg-open %s1", orphan = true, block = false, desc = "Explorer" },
]
ide = [
	{ run = "zed %s1", orphan = true, block = false, desc = "Zed" },
]

[open]
prepend_rules = [
    { mime = "folder/*", use = ["explorer", "ide"] },
    { mime = "text/*", use = ["vim", "ide"] },
    { mime = "application/*", use = ["vim", "ide" ] },
]
