[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[preview]
ueberzug_offset = [-0.5, 1, 0.0, 0.0]

[opener]
vim = [
    { run = "vim %s", block = true }
]
explorer = [
	{ run = "xdg-open %s1", orphan = true, desc = "Explorer" },
]
ide = [
	{ run = "zed %s1", orphan = true, desc = "Zed" },
]

[open]
prepend_rules = [
    { mime = "folder/*", use = ["ide", "explorer"] },
    { mime = "text/*", use = ["vim", "ide"] },
]
